"""
Django settings for portfolioApp project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'wdhyoce51wr2oe1t4@pzxl_-!yn+uw#bizqyt+t&00j1oh4+r7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

ALLOWED_HOSTS = ['oladev.herokuapp.com','127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djrichtextfield',
    'blog',
    "project",
    "pwa",
    'cloudinary',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolioApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'project/templates/project',
            BASE_DIR / 'blog/templates/blog'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolioApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUD_NAME'),
    'API_KEY': config('API_KEY'),
    'API_SECRET': config('API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


DJRICHTEXTFIELD_CONFIG = {
    'js': ['//cdn.tiny.cloud/1/tpvw1y2jhm6yn7y9i81hdkh74quqj2jeorqi1fdduuvj894c/tinymce/5/tinymce.min.js'],
    'init_template': 'djrichtextfield/init/tinymce.js',
    'settings': {
        'menubar': False,
        'plugins': 'link image',
        'toolbar': 'bold italic | link image | removeformat',
        'width': 700
    }
} 

PWA_SERVICE_WORKER_PATH = BASE_DIR / 'project/static/project/js/serviceWorker.js'

PWA_APP_NAME = 'Olawale'
PWA_APP_DESCRIPTION = "Mustapha Moshood Olawale | Full-stack developer and Geospatial Software Developer and Analyst experienced in building functional and scalable web applications with different technologies and integrations to Gis, Data Science and Artificial Intelligence."
PWA_APP_THEME_COLOR = '#18d26e'
PWA_APP_BACKGROUND_COLOR = '#000000'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait-primary'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
       "src": "/static/project/img/android-icon-36x36.png",
       "sizes": "36x36",
       "type": "image/png",
       "density": "0.75"
    },
    {
       "src": "/static/project/img/android-icon-48x48.png",
       "sizes": "48x48",
       "type": "image/png",
       "density": "1.0"
    },
    {
       "src": "/static/project/img/android-icon-72x72.png",
       "sizes": "72x72",
       "type": "image/png",
       "density": "1.5"
    },
    {
       "src": "/static/project/img/android-icon-96x96.png",
       "sizes": "96x96",
       "type": "image/png",
       "density": "2.0"
    },
    {
       "src": "/static/project/img/android-icon-144x144.png",
       "sizes": "144x144",
       "type": "image/png",
       "density": "3.0"
    },
    {
       "src": "/static/project/img/android-icon-192x192.png",
       "sizes": "192x192",
       "type": "image/png",
       "density": "4.0"
    },
    {
       "src": "/static/project/img/android-icon-512x512.png",
       "sizes": "512x512",
       "type": "image/png",
       "density": "5.0"
    }
]
PWA_APP_ICONS_APPLE = [
    {
       "src": "/static/project/img/apple-icon-57x57.png",
       "sizes": "57x57",
       "type": "image/png"
    },
    {
       "src": "/static/project/img/apple-icon-60x60.png",
       "sizes": "60x60",
       "type": "image/png"
    },
    {
       "src": "/static/project/img/apple-icon-72x72.png",
       "sizes": "72x72",
       "type": "image/png"
    },
    {
       "src": "/static/project/img/apple-icon-76x76.png",
       "sizes": "76x76",
       "type": "image/png"
    },
    {
       "src": "/static/project/img/apple-icon-114x114.png",
       "sizes": "114x114",
       "type": "image/png"
    },
    {
       "src": "/static/project/img/apple-icon-120x120.png",
       "sizes": "120x120",
       "type": "image/png"
    },
    {
       "src": "/static/project/img/apple-icon-144x144.png",
       "sizes": "144x144",
       "type": "image/png"
    },
    {
       "src": "/static/project/img/apple-icon-152x152.png",
       "sizes": "152x152",
       "type": "image/png"
    },
    {
       "src": "/static/project/img/apple-icon-180x180.png",
       "sizes": "180x180",
       "type": "image/png"
    },
    {
       "src": "/static/project/img/apple-icon-512x512.png",
       "sizes": "512x512",
       "type": "image/png"
    }
]
PWA_APP_SPLASH_SCREEN = [

]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'    
PWA_APP_DEBUG_MODE = False

X_FRAME_OPTIONS = 'SAMEORIGIN'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

import dj_database_url
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')