# Generated by Django 3.1.2 on 2020-10-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='about/images/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('description_two', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=250)),
                ('freelance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.CharField(max_length=100)),
                ('projects', models.CharField(max_length=100)),
                ('hours_of_support', models.CharField(max_length=100)),
                ('years_of_experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('years', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('years', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('details_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('filters', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project/images/')),
                ('url', models.URLField(blank=True)),
                ('image_1', models.ImageField(blank=True, upload_to='project/images/')),
                ('image_2', models.ImageField(blank=True, upload_to='project/images/')),
                ('image_3', models.ImageField(blank=True, upload_to='project/images/')),
                ('stack', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('site_slider', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('site_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('percent', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('percent', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('details_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('testimony', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='testimonials/images')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsAap'), ('linkedin', 'LinkedIn'), ('github', 'Github')], max_length=50)),
                ('link', models.URLField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.sitedetail')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=14)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.sitedetail')),
            ],
        ),
    ]
