# Generated by Django 3.1.2 on 2020-10-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='counts',
            options={'verbose_name_plural': 'Counts'},
        ),
        migrations.AlterModelOptions(
            name='skillsleft',
            options={'verbose_name_plural': 'SkillsLeft'},
        ),
        migrations.AlterModelOptions(
            name='skillsright',
            options={'verbose_name_plural': 'SkillsRight'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='sitesocial',
            name='github',
            field=models.URLField(default='https://github.com/olawale1rty'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sitesocial',
            name='social_media',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsAap'), ('linkedin', 'LinkedIn')], max_length=50),
        ),
        migrations.CreateModel(
            name='SummaryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_detail', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.summary')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_detail', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.experience')),
            ],
        ),
    ]
