# Generated by Django 3.1.2 on 2020-10-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201016_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='details_list',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='details_list',
        ),
        migrations.AlterField(
            model_name='sitesocial',
            name='social_media',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn')], max_length=50),
        ),
    ]
