# Generated by Django 3.1.2 on 2020-10-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20201016_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publication_status',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=60),
        ),
    ]
